
import {strEnum} from "../../helpers/str-enum";
import {AttributeIdConstTypes} from "./system-attributes-store";
import {AggregateDataStore} from "../aggregate-datastore";
import {SystemDataStore} from "./system-data-store";
import {SystemDataAggregators} from "../data-aggregators/system-data-aggregators";
export const SkillDifficultyConsts = strEnum(["E", "A", "H", "VH"]);
export type SkillDifficultyConstsTypes = keyof typeof SkillDifficultyConsts;



type Skill = {
    skillId:string;
    name: string;
    attributeId: AttributeIdConstTypes;
    difficulty: SkillDifficultyConstsTypes
}

type SkillListStore = { [skillId: string]: Skill };


const SystemSkillsListStoreInitialState: SkillListStore = {
    animalHandling:{skillId:"animalHandling", name:"Animal Handling",attributeId:"iq",difficulty:"A"},
    anthropology:{skillId:"anthropology", name:"Anthropology",attributeId:"iq",difficulty:"H"},
    areaKnowledge:{skillId:"areaKnowledge", name:"Area Knowledge",attributeId:"iq",difficulty:"E"},
    armoury:{skillId:"armoury", name:"Armoury",attributeId:"iq",difficulty:"A"},
    artillery:{skillId:"artillery", name:"Artillery",attributeId:"iq",difficulty:"A"},
    artist:{skillId:"artist", name:"Artist",attributeId:"iq",difficulty:"H"},
    beamWeapons:{skillId:"beamWeapons", name:"Beam Weapons",attributeId:"dx",difficulty:"E"},
    bioengineering:{skillId:"bioengineering", name:"Bioengineering",attributeId:"iq",difficulty:"H"},
    biology:{skillId:"biology", name:"Biology",attributeId:"iq",difficulty:"VH"},
    boating:{skillId:"boating", name:"Boating",attributeId:"dx",difficulty:"A"},
    connoisseur:{skillId:"connoisseur", name:"Connoisseur",attributeId:"iq",difficulty:"A"},
    currentAffairs:{skillId:"currentAffairs", name:"Current Affairs",attributeId:"iq",difficulty:"E"},
    disguise:{skillId:"disguise", name:"Disguise",attributeId:"iq",difficulty:"A"},
    driving:{skillId:"driving", name:"Driving",attributeId:"dx",difficulty:"A"},
    electronicsOperation:{skillId:"electronicsOperation", name:"Electronics Operation",attributeId:"iq",difficulty:"A"},
    electronicsRepair:{skillId:"electronicsRepair", name:"Electronics Repair",attributeId:"iq",difficulty:"A"},
    engineer:{skillId:"engineer", name:"Engineer",attributeId:"iq",difficulty:"H"},
    expertSkill:{skillId:"expertSkill", name:"Expert Skill",attributeId:"iq",difficulty:"H"},
    explosives:{skillId:"explosives", name:"Explosives",attributeId:"iq",difficulty:"A"},
    fastDraw:{skillId:"fastDraw", name:"Fast-Draw",attributeId:"dx",difficulty:"E"},
    fortuneTelling:{skillId:"fortuneTelling", name:"Fortune-Telling",attributeId:"iq",difficulty:"A"},
    games:{skillId:"games", name:"Games",attributeId:"iq",difficulty:"E"},
    geography:{skillId:"geography", name:"Geography",attributeId:"iq",difficulty:"H"},
    geology:{skillId:"geology", name:"Geology",attributeId:"iq",difficulty:"H"},
    groupPerformance:{skillId:"groupPerformance", name:"Group Performance",attributeId:"iq",difficulty:"A"},
    gunner:{skillId:"gunner", name:"Gunner",attributeId:"dx",difficulty:"E"},
    gunsPistol:{skillId:"gunsPistol", name:"Guns/Pistol",attributeId:"dx",difficulty:"E"},
    gunsRifle:{skillId:"gunsRifle", name:"Guns/Rifle",attributeId:"dx",difficulty:"E"},
    hazardousMaterials:{skillId:"hazardousMaterials", name:"Hazardous Materials",attributeId:"iq",difficulty:"A"},
    hiddenLore:{skillId:"hiddenLore", name:"Hidden Lore",attributeId:"iq",difficulty:"A"},
    history:{skillId:"history", name:"History",attributeId:"iq",difficulty:"H"},
    innateAttack:{skillId:"innateAttack", name:"Innate Attack",attributeId:"dx",difficulty:"E"},
    law:{skillId:"law", name:"Law",attributeId:"iq",difficulty:"H"},
    liquidProjector:{skillId:"liquidProjector", name:"Liquid Projector",attributeId:"dx",difficulty:"E"},
    mathematics:{skillId:"mathematics", name:"Mathematics",attributeId:"iq",difficulty:"H"},
    mechanic:{skillId:"mechanic", name:"Mechanic",attributeId:"iq",difficulty:"A"},
    meteorology:{skillId:"meteorology", name:"Meteorology",attributeId:"iq",difficulty:"A"},
    mimicry:{skillId:"mimicry", name:"Mimicry",attributeId:"iq",difficulty:"H"},
    musicalInstrument:{skillId:"musicalInstrument", name:"Musical Instrument",attributeId:"iq",difficulty:"H"},
    naturalist:{skillId:"naturalist", name:"Naturalist",attributeId:"iq",difficulty:"H"},
    navigation:{skillId:"navigation", name:"Navigation",attributeId:"iq",difficulty:"A"},
    paleontology:{skillId:"paleontology", name:"Paleontology",attributeId:"iq",difficulty:"H"},
    pharmacy:{skillId:"pharmacy", name:"Pharmacy",attributeId:"iq",difficulty:"H"},
    philosophy:{skillId:"philosophy", name:"Philosophy",attributeId:"iq",difficulty:"H"},
    physiology:{skillId:"physiology", name:"Physiology",attributeId:"iq",difficulty:"H"},
    piloting:{skillId:"piloting", name:"Piloting",attributeId:"dx",difficulty:"A"},
    religiousRitual:{skillId:"religiousRitual", name:"Religious Ritual",attributeId:"iq",difficulty:"H"},
    riding:{skillId:"riding", name:"Riding",attributeId:"dx",difficulty:"A"},
    ritualMagic:{skillId:"ritualMagic", name:"Ritual Magic",attributeId:"iq",difficulty:"VH"},
    savoirFaire:{skillId:"savoirFaire", name:"Savoir-Faire",attributeId:"iq",difficulty:"E"},
    shield:{skillId:"shield", name:"Shield",attributeId:"dx",difficulty:"E"},
    shipHandling:{skillId:"shipHandling", name:"Shiphandling",attributeId:"iq",difficulty:"H"},
    smith:{skillId:"smith", name:"Smith",attributeId:"iq",difficulty:"A"},
    strategy:{skillId:"strategy", name:"Strategy",attributeId:"iq",difficulty:"H"},
    submarine:{skillId:"submarine", name:"Submarine",attributeId:"dx",difficulty:"A"},
    survival:{skillId:"survival", name:"Survival",attributeId:"per",difficulty:"A"},
    symbolDrawing:{skillId:"symbolDrawing", name:"Symbol Drawing",attributeId:"iq",difficulty:"H"},
    teamster:{skillId:"teamster", name:"Teamster",attributeId:"iq",difficulty:"A"},
    theology:{skillId:"theology", name:"Theology",attributeId:"iq",difficulty:"H"},
    thrownWeapon:{skillId:"thrownWeapon", name:"Thrown Weapon",attributeId:"dx",difficulty:"E"},
    accounting:{skillId:"accounting", name:"Accounting",attributeId:"iq",difficulty:"H"},
    acrobatics:{skillId:"acrobatics", name:"Acrobatics",attributeId:"dx",difficulty:"H"},
    acting:{skillId:"acting", name:"Acting",attributeId:"iq",difficulty:"A"},
    administration:{skillId:"administration", name:"Administration",attributeId:"iq",difficulty:"A"},
    aerobatics:{skillId:"aerobatics", name:"Aerobatics",attributeId:"dx",difficulty:"H"},
    airshipman:{skillId:"airshipman", name:"Airshipman",attributeId:"iq",difficulty:"E"},
    alchemy:{skillId:"alchemy", name:"Alchemy",attributeId:"iq",difficulty:"VH"},
    aquabatics:{skillId:"aquabatics", name:"Aquabatics",attributeId:"dx",difficulty:"H"},
    archaeology:{skillId:"archaeology", name:"Archaeology",attributeId:"iq",difficulty:"H"},
    architecture:{skillId:"architecture", name:"Architecture",attributeId:"iq",difficulty:"A"},
    astronomy:{skillId:"astronomy", name:"Astronomy",attributeId:"iq",difficulty:"H"},
    autohypnosis:{skillId:"autohypnosis", name:"Autohypnosis",attributeId:"will",difficulty:"H"},
    axeMace:{skillId:"axeMace", name:"Axe/Mace",attributeId:"dx",difficulty:"A"},
    battlesuit:{skillId:"battlesuit", name:"Battlesuit",attributeId:"dx",difficulty:"A"},
    bicycling:{skillId:"bicycling", name:"Bicycling",attributeId:"dx",difficulty:"E"},
    blindFighting:{skillId:"blindFighting", name:"Blind Fighting",attributeId:"per",difficulty:"VH"},
    blowpipe:{skillId:"blowpipe", name:"Blowpipe",attributeId:"dx",difficulty:"H"},
    bodyControl:{skillId:"bodyControl", name:"Body Control",attributeId:"ht",difficulty:"VH"},
    bodyLanguage:{skillId:"bodyLanguage", name:"Body Language",attributeId:"per",difficulty:"A"},
    bodySense:{skillId:"bodySense", name:"Body Sense",attributeId:"dx",difficulty:"H"},
    bolas:{skillId:"bolas", name:"Bolas",attributeId:"dx",difficulty:"A"},
    bow:{skillId:"bow", name:"Bow",attributeId:"dx",difficulty:"A"},
    boxing:{skillId:"boxing", name:"Boxing",attributeId:"dx",difficulty:"A"},
    brainHacking:{skillId:"brainHacking", name:"Brain Hacking",attributeId:"iq",difficulty:"H"},
    brainwashing:{skillId:"brainwashing", name:"Brainwashing",attributeId:"iq",difficulty:"H"},
    brawling:{skillId:"brawling", name:"Brawling",attributeId:"dx",difficulty:"E"},
    breakingBlow:{skillId:"breakingBlow", name:"Breaking Blow",attributeId:"iq",difficulty:"H"},
    breathControl:{skillId:"breathControl", name:"Breath Control",attributeId:"ht",difficulty:"H"},
    broadsword:{skillId:"broadsword", name:"Broadsword",attributeId:"dx",difficulty:"A"},
    camouflage:{skillId:"camouflage", name:"Camouflage",attributeId:"iq",difficulty:"E"},
    captivate:{skillId:"captivate", name:"Captivate",attributeId:"will",difficulty:"H"},
    carousing:{skillId:"carousing", name:"Carousing",attributeId:"ht",difficulty:"E"},
    carpentry:{skillId:"carpentry", name:"Carpentry",attributeId:"iq",difficulty:"E"},
    cartography:{skillId:"cartography", name:"Cartography",attributeId:"iq",difficulty:"A"},
    chemistry:{skillId:"chemistry", name:"Chemistry",attributeId:"iq",difficulty:"H"},
    climbing:{skillId:"climbing", name:"Climbing",attributeId:"dx",difficulty:"A"},
    cloak:{skillId:"cloak", name:"Cloak",attributeId:"dx",difficulty:"A"},
    computerHacking:{skillId:"computerHacking", name:"Computer Hacking",attributeId:"iq",difficulty:"VH"},
    computerOperation:{skillId:"computerOperation", name:"Computer Operation",attributeId:"iq",difficulty:"E"},
    computerProgramming:{skillId:"computerProgramming", name:"Computer Programming",attributeId:"iq",difficulty:"H"},
    cooking:{skillId:"cooking", name:"Cooking",attributeId:"iq",difficulty:"A"},
    counterfeiting:{skillId:"counterfeiting", name:"Counterfeiting",attributeId:"iq",difficulty:"H"},
    crewman:{skillId:"crewman", name:"Crewman",attributeId:"iq",difficulty:"E"},
    criminology:{skillId:"criminology", name:"Criminology",attributeId:"iq",difficulty:"A"},
    crossbow:{skillId:"crossbow", name:"Crossbow",attributeId:"dx",difficulty:"E"},
    cryptography:{skillId:"cryptography", name:"Cryptography",attributeId:"iq",difficulty:"H"},
    dancing:{skillId:"dancing", name:"Dancing",attributeId:"dx",difficulty:"A"},
    detectLies:{skillId:"detectLies", name:"Detect Lies",attributeId:"per",difficulty:"H"},
    diagnosis:{skillId:"diagnosis", name:"Diagnosis",attributeId:"iq",difficulty:"H"},
    diplomacy:{skillId:"diplomacy", name:"Diplomacy",attributeId:"iq",difficulty:"H"},
    divingSuit:{skillId:"divingSuit", name:"Diving Suit",attributeId:"dx",difficulty:"A"},
    dreaming:{skillId:"dreaming", name:"Dreaming",attributeId:"will",difficulty:"H"},
    dropping:{skillId:"dropping", name:"Dropping",attributeId:"dx",difficulty:"A"},
    economics:{skillId:"economics", name:"Economics",attributeId:"iq",difficulty:"H"},
    electrician:{skillId:"electrician", name:"Electrician",attributeId:"iq",difficulty:"A"},
    enthrallment:{skillId:"enthrallment", name:"Enthrallment",attributeId:"will",difficulty:"H"},
    environmentSuit:{skillId:"environmentSuit", name:"Environment Suit",attributeId:"dx",difficulty:"A"},
    eroticArt:{skillId:"eroticArt", name:"Erotic Art",attributeId:"dx",difficulty:"A"},
    escape:{skillId:"escape", name:"Escape",attributeId:"dx",difficulty:"H"},
    esotericMedicine:{skillId:"esotericMedicine", name:"Esoteric Medicine",attributeId:"per",difficulty:"H"},
    exorcism:{skillId:"exorcism", name:"Exorcism",attributeId:"will",difficulty:"H"},
    falconry:{skillId:"falconry", name:"Falconry",attributeId:"iq",difficulty:"A"},
    farming:{skillId:"farming", name:"Farming",attributeId:"iq",difficulty:"A"},
    fastTalk:{skillId:"fastTalk", name:"Fast-Talk",attributeId:"iq",difficulty:"A"},
    filch:{skillId:"filch", name:"Filch",attributeId:"dx",difficulty:"A"},
    finance:{skillId:"finance", name:"Finance",attributeId:"iq",difficulty:"H"},
    fireEating:{skillId:"fireEating", name:"Fire Eating",attributeId:"dx",difficulty:"A"},
    firstAid:{skillId:"firstAid", name:"First Aid",attributeId:"iq",difficulty:"E"},
    fishing:{skillId:"fishing", name:"Fishing",attributeId:"per",difficulty:"E"},
    flail:{skillId:"flail", name:"Flail",attributeId:"dx",difficulty:"H"},
    flight:{skillId:"flight", name:"Flight",attributeId:"ht",difficulty:"A"},
    flyingLeap:{skillId:"flyingLeap", name:"Flying Leap",attributeId:"iq",difficulty:"H"},
    forceSword:{skillId:"forceSword", name:"Force Sword",attributeId:"dx",difficulty:"A"},
    forceWhip:{skillId:"forceWhip", name:"Force Whip",attributeId:"dx",difficulty:"A"},
    forcedEntry:{skillId:"forcedEntry", name:"Forced Entry",attributeId:"dx",difficulty:"E"},
    forensics:{skillId:"forensics", name:"Forensics",attributeId:"iq",difficulty:"H"},
    forgery:{skillId:"forgery", name:"Forgery",attributeId:"iq",difficulty:"H"},
    forwardObserver:{skillId:"forwardObserver", name:"Forward Observer",attributeId:"iq",difficulty:"A"},
    freeFall:{skillId:"freeFall", name:"Free Fall",attributeId:"dx",difficulty:"A"},
    freightHandling:{skillId:"freightHandling", name:"Freight Handling",attributeId:"iq",difficulty:"A"},
    gambling:{skillId:"gambling", name:"Gambling",attributeId:"iq",difficulty:"A"},
    gardening:{skillId:"gardening", name:"Gardening",attributeId:"iq",difficulty:"E"},
    garrote:{skillId:"garrote", name:"Garrote",attributeId:"dx",difficulty:"E"},
    gesture:{skillId:"gesture", name:"Gesture",attributeId:"iq",difficulty:"E"},
    heraldry:{skillId:"heraldry", name:"Heraldry",attributeId:"iq",difficulty:"A"},
    herbLore:{skillId:"herbLore", name:"Herb Lore",attributeId:"iq",difficulty:"VH"},
    hiking:{skillId:"hiking", name:"Hiking",attributeId:"ht",difficulty:"A"},
    hobbySkillPhysical:{skillId:"hobbySkillPhysical", name:"Hobby Skill (Physical)",attributeId:"dx",difficulty:"E"},
    hobbySkillMental:{skillId:"hobbySkillMental", name:"Hobby Skill (Mental)",attributeId:"iq",difficulty:"E"},
    holdout:{skillId:"holdout", name:"Holdout",attributeId:"iq",difficulty:"A"},
    housekeeping:{skillId:"housekeeping", name:"Housekeeping",attributeId:"iq",difficulty:"E"},
    hypnotism:{skillId:"hypnotism", name:"Hypnotism",attributeId:"iq",difficulty:"H"},
    immovableStance:{skillId:"immovableStance", name:"Immovable Stance",attributeId:"dx",difficulty:"H"},
    intelligenceAnalysis:{skillId:"intelligenceAnalysis", name:"Intelligence Analysis",attributeId:"iq",difficulty:"H"},
    interrogation:{skillId:"interrogation", name:"Interrogation",attributeId:"iq",difficulty:"A"},
    intimidation:{skillId:"intimidation", name:"Intimidation",attributeId:"will",difficulty:"A"},
    invisibilityArt:{skillId:"invisibilityArt", name:"Invisibility Art",attributeId:"iq",difficulty:"VH"},
    jeweler:{skillId:"jeweler", name:"Jeweler",attributeId:"iq",difficulty:"H"},
    jitteSai:{skillId:"jitteSai", name:"Jitte/Sai",attributeId:"dx",difficulty:"A"},
    judo:{skillId:"judo", name:"Judo",attributeId:"dx",difficulty:"H"},
    jumping:{skillId:"jumping", name:"Jumping",attributeId:"dx",difficulty:"E"},
    karate:{skillId:"karate", name:"Karate",attributeId:"dx",difficulty:"H"},
    kiai:{skillId:"kiai", name:"Kiai",attributeId:"ht",difficulty:"H"},
    knife:{skillId:"knife", name:"Knife",attributeId:"dx",difficulty:"E"},
    knotTying:{skillId:"knotTying", name:"Knot-Tying",attributeId:"dx",difficulty:"E"},
    kusari:{skillId:"kusari", name:"Kusari",attributeId:"dx",difficulty:"H"},
    lance:{skillId:"lance", name:"Lance",attributeId:"dx",difficulty:"A"},
    lasso:{skillId:"lasso", name:"Lasso",attributeId:"dx",difficulty:"A"},
    leadership:{skillId:"leadership", name:"Leadership",attributeId:"iq",difficulty:"A"},
    leatherworking:{skillId:"leatherworking", name:"Leatherworking",attributeId:"dx",difficulty:"E"},
    lifting:{skillId:"lifting", name:"Lifting",attributeId:"ht",difficulty:"A"},
    lightWalk:{skillId:"lightWalk", name:"Light Walk",attributeId:"dx",difficulty:"H"},
    linguistics:{skillId:"linguistics", name:"Linguistics",attributeId:"iq",difficulty:"H"},
    lipReading:{skillId:"lipReading", name:"Lip Reading",attributeId:"per",difficulty:"A"},
    literature:{skillId:"literature", name:"Literature",attributeId:"iq",difficulty:"H"},
    lockpicking:{skillId:"lockpicking", name:"Lockpicking",attributeId:"iq",difficulty:"A"},
    machinist:{skillId:"machinist", name:"Machinist",attributeId:"iq",difficulty:"A"},
    mainGauche:{skillId:"mainGauche", name:"Main-Gauche",attributeId:"dx",difficulty:"A"},
    makeup:{skillId:"makeup", name:"Makeup",attributeId:"iq",difficulty:"E"},
    marketAnalysis:{skillId:"marketAnalysis", name:"Market Analysis",attributeId:"iq",difficulty:"H"},
    masonry:{skillId:"masonry", name:"Masonry",attributeId:"iq",difficulty:"E"},
    meditation:{skillId:"meditation", name:"Meditation",attributeId:"will",difficulty:"H"},
    mentalStrength:{skillId:"mentalStrength", name:"Mental Strength",attributeId:"will",difficulty:"E"},
    merchant:{skillId:"merchant", name:"Merchant",attributeId:"iq",difficulty:"A"},
    metallurgy:{skillId:"metallurgy", name:"Metallurgy",attributeId:"iq",difficulty:"H"},
    mindBlock:{skillId:"mindBlock", name:"Mind Block",attributeId:"will",difficulty:"A"},
    monowireWhip:{skillId:"monowireWhip", name:"Monowire Whip",attributeId:"dx",difficulty:"H"},
    mount:{skillId:"mount", name:"Mount",attributeId:"dx",difficulty:"A"},
    musicalComposition:{skillId:"musicalComposition", name:"Musical Composition",attributeId:"iq",difficulty:"H"},
    musicalInfluence:{skillId:"musicalInfluence", name:"Musical Influence",attributeId:"iq",difficulty:"VH"},
    nbcSuit:{skillId:"nbcSuit", name:"NBC Suit",attributeId:"dx",difficulty:"A"},
    net:{skillId:"net", name:"Net",attributeId:"dx",difficulty:"H"},
    observation:{skillId:"observation", name:"Observation",attributeId:"per",difficulty:"A"},
    occultism:{skillId:"occultism", name:"Occultism",attributeId:"iq",difficulty:"A"},
    packing:{skillId:"packing", name:"Packing",attributeId:"iq",difficulty:"A"},
    panhandling:{skillId:"panhandling", name:"Panhandling",attributeId:"iq",difficulty:"E"},
    parachuting:{skillId:"parachuting", name:"Parachuting",attributeId:"dx",difficulty:"E"},
    parryMissileWeapons:{skillId:"parryMissileWeapons", name:"Parry Missile Weapons",attributeId:"dx",difficulty:"H"},
    performance:{skillId:"performance", name:"Performance",attributeId:"iq",difficulty:"A"},
    persuade:{skillId:"persuade", name:"Persuade",attributeId:"will",difficulty:"H"},
    photography:{skillId:"photography", name:"Photography",attributeId:"iq",difficulty:"A"},
    physician:{skillId:"physician", name:"Physician",attributeId:"iq",difficulty:"H"},
    physics:{skillId:"physics", name:"Physics",attributeId:"iq",difficulty:"VH"},
    pickpocket:{skillId:"pickpocket", name:"Pickpocket",attributeId:"dx",difficulty:"H"},
    poetry:{skillId:"poetry", name:"Poetry",attributeId:"iq",difficulty:"A"},
    poisons:{skillId:"poisons", name:"Poisons",attributeId:"iq",difficulty:"H"},
    polearm:{skillId:"polearm", name:"Polearm",attributeId:"dx",difficulty:"A"},
    politics:{skillId:"politics", name:"Politics",attributeId:"iq",difficulty:"A"},
    powerBlow:{skillId:"powerBlow", name:"Power Blow",attributeId:"will",difficulty:"H"},
    pressurePoints:{skillId:"pressurePoints", name:"Pressure Points",attributeId:"iq",difficulty:"H"},
    pressureSecrets:{skillId:"pressureSecrets", name:"Pressure Secrets",attributeId:"iq",difficulty:"VH"},
    professionalSkillPhysical:{skillId:"professionalSkillPhysical", name:"Professional Skill (Physical)",attributeId:"dx",difficulty:"A"},
    professionalSkillMental:{skillId:"professionalSkillMental", name:"Professional Skill (Mental)",attributeId:"iq",difficulty:"A"},
    propaganda:{skillId:"propaganda", name:"Propaganda",attributeId:"iq",difficulty:"A"},
    prospecting:{skillId:"prospecting", name:"Prospecting",attributeId:"iq",difficulty:"A"},
    psychology:{skillId:"psychology", name:"Psychology",attributeId:"iq",difficulty:"H"},
    publicSpeaking:{skillId:"publicSpeaking", name:"Public Speaking",attributeId:"iq",difficulty:"A"},
    push:{skillId:"push", name:"Push",attributeId:"dx",difficulty:"H"},
    rapier:{skillId:"rapier", name:"Rapier",attributeId:"dx",difficulty:"A"},
    research:{skillId:"research", name:"Research",attributeId:"iq",difficulty:"A"},
    running:{skillId:"running", name:"Running",attributeId:"ht",difficulty:"A"},
    saber:{skillId:"saber", name:"Saber",attributeId:"dx",difficulty:"A"},
    scrounging:{skillId:"scrounging", name:"Scrounging",attributeId:"per",difficulty:"E"},
    scuba:{skillId:"scuba", name:"Scuba",attributeId:"iq",difficulty:"A"},
    seamanship:{skillId:"seamanship", name:"Seamanship",attributeId:"iq",difficulty:"E"},
    search:{skillId:"search", name:"Search",attributeId:"per",difficulty:"A"},
    sewing:{skillId:"sewing", name:"Sewing",attributeId:"dx",difficulty:"E"},
    sexAppeal:{skillId:"sexAppeal", name:"Sex Appeal",attributeId:"ht",difficulty:"A"},
    shadowing:{skillId:"shadowing", name:"Shadowing",attributeId:"iq",difficulty:"A"},
    shortsword:{skillId:"shortsword", name:"Shortsword",attributeId:"dx",difficulty:"A"},
    singing:{skillId:"singing", name:"Singing",attributeId:"ht",difficulty:"E"},
    skating:{skillId:"skating", name:"Skating",attributeId:"ht",difficulty:"H"},
    skiing:{skillId:"skiing", name:"Skiing",attributeId:"ht",difficulty:"H"},
    sleightOfHand:{skillId:"sleightOfHand", name:"Sleight of Hand",attributeId:"dx",difficulty:"H"},
    sling:{skillId:"sling", name:"Sling",attributeId:"dx",difficulty:"H"},
    smallsword:{skillId:"smallsword", name:"Smallsword",attributeId:"dx",difficulty:"A"},
    smuggling:{skillId:"smuggling", name:"Smuggling",attributeId:"iq",difficulty:"A"},
    sociology:{skillId:"sociology", name:"Sociology",attributeId:"iq",difficulty:"H"},
    soldier:{skillId:"soldier", name:"Soldier",attributeId:"iq",difficulty:"A"},
    spacer:{skillId:"spacer", name:"Spacer",attributeId:"iq",difficulty:"E"},
    spear:{skillId:"spear", name:"Spear",attributeId:"dx",difficulty:"A"},
    spearThrower:{skillId:"spearThrower", name:"Spear Thrower",attributeId:"dx",difficulty:"A"},
    speedReading:{skillId:"speedReading", name:"Speed-Reading",attributeId:"iq",difficulty:"A"},
    sports:{skillId:"sports", name:"Sports",attributeId:"dx",difficulty:"A"},
    staff:{skillId:"staff", name:"Staff",attributeId:"dx",difficulty:"A"},
    stageCombat:{skillId:"stageCombat", name:"Stage Combat",attributeId:"dx",difficulty:"A"},
    stealth:{skillId:"stealth", name:"Stealth",attributeId:"dx",difficulty:"A"},
    streetwise:{skillId:"streetwise", name:"Streetwise",attributeId:"iq",difficulty:"A"},
    submariner:{skillId:"submariner", name:"Submariner",attributeId:"iq",difficulty:"E"},
    suggest:{skillId:"suggest", name:"Suggest",attributeId:"will",difficulty:"H"},
    sumoWrestling:{skillId:"sumoWrestling", name:"Sumo Wrestling",attributeId:"dx",difficulty:"A"},
    surgery:{skillId:"surgery", name:"Surgery",attributeId:"iq",difficulty:"VH"},
    swayEmotions:{skillId:"swayEmotions", name:"Sway Emotions",attributeId:"will",difficulty:"H"},
    swimming:{skillId:"swimming", name:"Swimming",attributeId:"ht",difficulty:"E"},
    tactics:{skillId:"tactics", name:"Tactics",attributeId:"iq",difficulty:"H"},
    teaching:{skillId:"teaching", name:"Teaching",attributeId:"iq",difficulty:"A"},
    thaumatology:{skillId:"thaumatology", name:"Thaumatology",attributeId:"iq",difficulty:"VH"},
    throwing:{skillId:"throwing", name:"Throwing",attributeId:"dx",difficulty:"A"},
    throwingArt:{skillId:"throwingArt", name:"Throwing Art",attributeId:"dx",difficulty:"H"},
    tonfa:{skillId:"tonfa", name:"Tonfa",attributeId:"dx",difficulty:"A"},
    tracking:{skillId:"tracking", name:"Tracking",attributeId:"per",difficulty:"A"},
    traps:{skillId:"traps", name:"Traps",attributeId:"iq",difficulty:"A"},
    twoHandedAxeMace:{skillId:"twoHandedAxeMace", name:"Two-Handed Axe/Mace",attributeId:"dx",difficulty:"A"},
    twoHandedFlail:{skillId:"twoHandedFlail", name:"Two-Handed Flail",attributeId:"dx",difficulty:"H"},
    twoHandedSword:{skillId:"twoHandedSword", name:"Two-Handed Sword",attributeId:"dx",difficulty:"A"},
    typing:{skillId:"typing", name:"Typing",attributeId:"dx",difficulty:"E"},
    urbanSurvival:{skillId:"urbanSurvival", name:"Urban Survival",attributeId:"per",difficulty:"A"},
    vaccSuit:{skillId:"vaccSuit", name:"Vacc Suit",attributeId:"dx",difficulty:"A"},
    ventriloquism:{skillId:"ventriloquism", name:"Ventriloquism",attributeId:"iq",difficulty:"H"},
    veterinary:{skillId:"veterinary", name:"Veterinary",attributeId:"iq",difficulty:"H"},
    weatherSense:{skillId:"weatherSense", name:"Weather Sense",attributeId:"iq",difficulty:"A"},
    weirdScience:{skillId:"weirdScience", name:"Weird Science",attributeId:"iq",difficulty:"VH"},
    whip:{skillId:"whip", name:"Whip",attributeId:"dx",difficulty:"A"},
    wrestling:{skillId:"wrestling", name:"Wrestling",attributeId:"dx",difficulty:"A"},
    writing:{skillId:"writing", name:"Writing",attributeId:"iq",difficulty:"A"},
    zenArchery:{skillId:"zenArchery", name:"Zen Archery",attributeId:"iq",difficulty:"VH"}
}
const SkillDifficultyStart = {
    "E": 0,
    "A": -1,
    "H": -2,
    "VH": -3
}

const SkillDifficultyCost = [1,2,4,8,12,16,20,24,28];


type SkillsStore = {
    list: SkillListStore;
    getStartingRelativeLevel: (skillDifficulty:string)=>number,
    getCost: (skillDifficulty:string, relativeLevel: number)=>number,
    getSkillLevel: (state: AggregateDataStore, skillId:string)=>number
}


export const SystemSkillsStoreInitialState: SkillsStore = {
    list: SystemSkillsListStoreInitialState,
    getStartingRelativeLevel: (skillDifficulty:string):number =>{
        return SkillDifficultyStart[skillDifficulty]
    },
    getCost: (skillDifficulty:string, relativeLevel: number):number => {
        var normalizedRelativeSkill = relativeLevel-SkillDifficultyStart[skillDifficulty];
        return SkillDifficultyCost[normalizedRelativeSkill];
    },
    getSkillLevel: (state: AggregateDataStore, skillId:string):number => {
        var relativeSkill:number = state.character.skills[skillId].relativeLevel;
        var systemSkill = SystemDataStore.skills.list[skillId];
        var attributeId = systemSkill.attributeId;
        var systemAttribute = SystemDataStore.attributes[attributeId];

        var attributeValue:number;
        attributeValue = SystemDataAggregators.attributes(state, attributeId).value;


        return attributeValue+relativeSkill;
    }
}