
import {strEnum} from "../../helpers/str-enum";
import {AttributeIdConstTypes} from "./system-attributes-store";
export const SkillDifficultyConsts = strEnum(["E", "A", "H", "VH"]);
export type SkillDifficultyConstsTypes = keyof typeof SkillDifficultyConsts;



export type SysSkill = {
    skillId:string;
    name: string;
    attributeId: AttributeIdConstTypes;
    difficulty: SkillDifficultyConstsTypes;
    default?:string;
    page?:string;
}

type SkillListStore = { [skillId: string]: SysSkill };

const SystemSkillsListStoreInitialState: SkillListStore =
    {
        accounting:{skillId:"accounting",name:"Accounting",attributeId:"iq",difficulty:"H",default:"-6",page:"174"},
        acrobatics:{skillId:"acrobatics",name:"Acrobatics",attributeId:"dx",difficulty:"H",default:"-6",page:"174"},
        acting:{skillId:"acting",name:"Acting",attributeId:"iq",difficulty:"A",default:"-5",page:"174"},
        administration:{skillId:"administration",name:"Administration",attributeId:"iq",difficulty:"A",default:"-5",page:"174"},
        aerobatics:{skillId:"aerobatics",name:"Aerobatics",attributeId:"dx",difficulty:"H",default:"-6",page:"174"},
        airshipman:{skillId:"airshipman",name:"Airshipman",attributeId:"iq",difficulty:"E",default:"-4",page:"185"},
        alchemy:{skillId:"alchemy",name:"Alchemy",attributeId:"iq",difficulty:"VH",default:"-999",page:"174"},
        animalHandling:{skillId:"animalHandling",name:"Animal Handling",attributeId:"iq",difficulty:"A",default:"-5",page:"175"},
        anthropology:{skillId:"anthropology",name:"Anthropology",attributeId:"iq",difficulty:"H",default:"-6",page:"175"},
        aquabatics:{skillId:"aquabatics",name:"Aquabatics",attributeId:"dx",difficulty:"H",default:"-6",page:"174"},
        archaeology:{skillId:"archaeology",name:"Archaeology",attributeId:"iq",difficulty:"H",default:"-6",page:"176"},
        architecture:{skillId:"architecture",name:"Architecture",attributeId:"iq",difficulty:"A",default:"-5",page:"176"},
        areaKnowledge:{skillId:"areaKnowledge",name:"Area Knowledge",attributeId:"iq",difficulty:"E",default:"-4",page:"176"},
        armoury:{skillId:"armoury",name:"Armoury",attributeId:"iq",difficulty:"A",default:"-5",page:"178"},
        artillery:{skillId:"artillery",name:"Artillery",attributeId:"iq",difficulty:"A",default:"-5",page:"178"},
        artist:{skillId:"artist",name:"Artist",attributeId:"iq",difficulty:"H",default:"-6",page:"179"},
        astronomy:{skillId:"astronomy",name:"Astronomy",attributeId:"iq",difficulty:"H",default:"-6",page:"179"},
        autohypnosis:{skillId:"autohypnosis",name:"Autohypnosis",attributeId:"will",difficulty:"H",default:"-999",page:"179"},
        axeMace:{skillId:"axeMace",name:"Axe/Mace",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        battlesuit:{skillId:"battlesuit",name:"Battlesuit",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        beamWeapons:{skillId:"beamWeapons",name:"Beam Weapons",attributeId:"dx",difficulty:"E",default:"-4",page:"179"},
        bicycling:{skillId:"bicycling",name:"Bicycling",attributeId:"dx",difficulty:"E",default:"-4",page:"180"},
        bioengineering:{skillId:"bioengineering",name:"Bioengineering",attributeId:"iq",difficulty:"H",default:"-999",page:"180"},
        biology:{skillId:"biology",name:"Biology",attributeId:"iq",difficulty:"VH",default:"-6",page:"180"},
        blindFighting:{skillId:"blindFighting",name:"Blind Fighting",attributeId:"per",difficulty:"VH",default:"-999",page:"180"},
        blowpipe:{skillId:"blowpipe",name:"Blowpipe",attributeId:"dx",difficulty:"H",default:"-6",page:"180"},
        boating:{skillId:"boating",name:"Boating",attributeId:"dx",difficulty:"A",default:"-5",page:"180"},
        bodyControl:{skillId:"bodyControl",name:"Body Control",attributeId:"ht",difficulty:"VH",default:"-999",page:"181"},
        bodyLanguage:{skillId:"bodyLanguage",name:"Body Language",attributeId:"per",difficulty:"A",default:"-999",page:"181"},
        bodySense:{skillId:"bodySense",name:"Body Sense",attributeId:"dx",difficulty:"H",default:"-6",page:"181"},
        bolas:{skillId:"bolas",name:"Bolas",attributeId:"dx",difficulty:"A",default:"-999",page:"181"},
        bow:{skillId:"bow",name:"Bow",attributeId:"dx",difficulty:"A",default:"-5",page:"182"},
        boxing:{skillId:"boxing",name:"Boxing",attributeId:"dx",difficulty:"A",default:"-999",page:"182"},
        brainHacking:{skillId:"brainHacking",name:"Brain Hacking",attributeId:"iq",difficulty:"H",default:"-999",page:"182"},
        brainwashing:{skillId:"brainwashing",name:"Brainwashing",attributeId:"iq",difficulty:"H",default:"-999",page:"182"},
        brawling:{skillId:"brawling",name:"Brawling",attributeId:"dx",difficulty:"E",default:"-999",page:"182"},
        breakingBlow:{skillId:"breakingBlow",name:"Breaking Blow",attributeId:"iq",difficulty:"H",default:"-999",page:"182"},
        breathControl:{skillId:"breathControl",name:"Breath Control",attributeId:"ht",difficulty:"H",default:"-999",page:"182"},
        broadsword:{skillId:"broadsword",name:"Broadsword",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        camouflage:{skillId:"camouflage",name:"Camouflage",attributeId:"iq",difficulty:"E",default:"-4",page:"183"},
        captivate:{skillId:"captivate",name:"Captivate",attributeId:"will",difficulty:"H",default:"-999",page:"191"},
        carousing:{skillId:"carousing",name:"Carousing",attributeId:"ht",difficulty:"E",default:"-4",page:"183"},
        carpentry:{skillId:"carpentry",name:"Carpentry",attributeId:"iq",difficulty:"E",default:"-4",page:"183"},
        cartography:{skillId:"cartography",name:"Cartography",attributeId:"iq",difficulty:"A",default:"-5",page:"183"},
        chemistry:{skillId:"chemistry",name:"Chemistry",attributeId:"iq",difficulty:"H",default:"-6",page:"183"},
        climbing:{skillId:"climbing",name:"Climbing",attributeId:"dx",difficulty:"A",default:"-5",page:"183"},
        cloak:{skillId:"cloak",name:"Cloak",attributeId:"dx",difficulty:"A",default:"-5",page:"184"},
        computerHacking:{skillId:"computerHacking",name:"Computer Hacking",attributeId:"iq",difficulty:"VH",default:"-999",page:"184"},
        computerOperation:{skillId:"computerOperation",name:"Computer Operation",attributeId:"iq",difficulty:"E",default:"-4",page:"184"},
        computerProgramming:{skillId:"computerProgramming", name:"Computer Programming",attributeId:"iq",difficulty:"H",default:"-999",page:"184"},
        connoisseur:{skillId:"connoisseur",name:"Connoisseur",attributeId:"iq",difficulty:"A",default:"-5",page:"185"},
        cooking:{skillId:"cooking",name:"Cooking",attributeId:"iq",difficulty:"A",default:"-5",page:"185"},
        counterfeiting:{skillId:"counterfeiting",name:"Counterfeiting",attributeId:"iq",difficulty:"H",default:"-6",page:"185"},
        crewman:{skillId:"crewman",name:"Crewman",attributeId:"iq",difficulty:"E",default:"-4",page:"185"},
        criminology:{skillId:"criminology",name:"Criminology",attributeId:"iq",difficulty:"A",default:"-5",page:"186"},
        crossbow:{skillId:"crossbow",name:"Crossbow",attributeId:"dx",difficulty:"E",default:"-4",page:"186"},
        cryptography:{skillId:"cryptography",name:"Cryptography",attributeId:"iq",difficulty:"H",default:"-999",page:"186"},
        currentAffairs:{skillId:"currentAffairs",name:"Current Affairs",attributeId:"iq",difficulty:"E",default:"-4",page:"186"},
        dancing:{skillId:"dancing",name:"Dancing",attributeId:"dx",difficulty:"A",default:"-5",page:"187"},
        detectLies:{skillId:"detectLies",name:"Detect Lies",attributeId:"per",difficulty:"H",default:"-6",page:"187"},
        diagnosis:{skillId:"diagnosis",name:"Diagnosis",attributeId:"iq",difficulty:"H",default:"-6",page:"187"},
        diplomacy:{skillId:"diplomacy",name:"Diplomacy",attributeId:"iq",difficulty:"H",default:"-6",page:"187"},
        disguise:{skillId:"disguise",name:"Disguise",attributeId:"iq",difficulty:"A",default:"-5",page:"187"},
        divingSuit:{skillId:"divingSuit",name:"Diving Suit",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        dreaming:{skillId:"dreaming",name:"Dreaming",attributeId:"will",difficulty:"H",default:"-6",page:"188"},
        driving:{skillId:"driving",name:"Driving",attributeId:"dx",difficulty:"A",default:"-5",page:"188"},
        dropping:{skillId:"dropping",name:"Dropping",attributeId:"dx",difficulty:"A",default:"-3",page:"189"},
        economics:{skillId:"economics",name:"Economics",attributeId:"iq",difficulty:"H",default:"-6",page:"189"},
        electrician:{skillId:"electrician",name:"Electrician",attributeId:"iq",difficulty:"A",default:"-5",page:"189"},
        electronicsOperation:{skillId:"electronicsOperation",name:"Electronics Operation",attributeId:"iq",difficulty:"A",default:"-5",page:"189"},
        electronicsRepair:{skillId:"electronicsRepair",name:"Electronics Repair",attributeId:"iq",difficulty:"A",default:"-5",page:"190"},
        engineer:{skillId:"engineer",name:"Engineer",attributeId:"iq",difficulty:"H",default:"-999",page:"190"},
        enthrallment:{skillId:"enthrallment",name:"Enthrallment",attributeId:"will",difficulty:"H",default:"-999",page:"191"},
        environmentSuit:{skillId:"environmentSuit",name:"Environment Suit",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        eroticArt:{skillId:"eroticArt",name:"Erotic Art",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        escape:{skillId:"escape",name:"Escape",attributeId:"dx",difficulty:"H",default:"-6",page:"192"},
        esotericMedicine:{skillId:"esotericMedicine",name:"Esoteric Medicine",attributeId:"per",difficulty:"H",default:"-6",page:"192"},
        exorcism:{skillId:"exorcism",name:"Exorcism",attributeId:"will",difficulty:"H",default:"-6",page:"193"},
        expertSkill:{skillId:"expertSkill",name:"Expert Skill",attributeId:"iq",difficulty:"H",default:"-999",page:"193"},
        explosives:{skillId:"explosives",name:"Explosives",attributeId:"iq",difficulty:"A",default:"-5",page:"194"},
        falconry:{skillId:"falconry",name:"Falconry",attributeId:"iq",difficulty:"A",default:"-5",page:"194"},
        farming:{skillId:"farming",name:"Farming",attributeId:"iq",difficulty:"A",default:"-5",page:"194"},
        fastDraw:{skillId:"fastDraw",name:"Fast-Draw",attributeId:"dx",difficulty:"E",default:"-999",page:"194"},
        fastTalk:{skillId:"fastTalk",name:"Fast-Talk",attributeId:"iq",difficulty:"A",default:"-5",page:"195"},
        filch:{skillId:"filch",name:"Filch",attributeId:"dx",difficulty:"A",default:"-5",page:"195"},
        finance:{skillId:"finance",name:"Finance",attributeId:"iq",difficulty:"H",default:"-999",page:"195"},
        fireEating:{skillId:"fireEating",name:"Fire Eating",attributeId:"dx",difficulty:"A",default:"-999",page:"195"},
        firstAid:{skillId:"firstAid",name:"First Aid",attributeId:"iq",difficulty:"E",default:"-4",page:"195"},
        fishing:{skillId:"fishing",name:"Fishing",attributeId:"per",difficulty:"E",default:"-4",page:"195"},
        flail:{skillId:"flail",name:"Flail",attributeId:"dx",difficulty:"H",default:"-999",page:"208"},
        flight:{skillId:"flight",name:"Flight",attributeId:"ht",difficulty:"A",default:"-5",page:"195"},
        flyingLeap:{skillId:"flyingLeap",name:"Flying Leap",attributeId:"iq",difficulty:"H",default:"-999",page:"196"},
        forceSword:{skillId:"forceSword",name:"Force Sword",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        forceWhip:{skillId:"forceWhip",name:"Force Whip",attributeId:"dx",difficulty:"A",default:"-999",page:"209"},
        forcedEntry:{skillId:"forcedEntry",name:"Forced Entry",attributeId:"dx",difficulty:"E",default:"-999",page:"196"},
        forensics:{skillId:"forensics",name:"Forensics",attributeId:"iq",difficulty:"H",default:"-6",page:"196"},
        forgery:{skillId:"forgery",name:"Forgery",attributeId:"iq",difficulty:"H",default:"-6",page:"196"},
        fortuneTelling:{skillId:"fortuneTelling",name:"Fortune-Telling",attributeId:"iq",difficulty:"A",default:"-5",page:"196"},
        forwardObserver:{skillId:"forwardObserver",name:"Forward Observer",attributeId:"iq",difficulty:"A",default:"-5",page:"196"},
        freeFall:{skillId:"freeFall",name:"Free Fall",attributeId:"dx",difficulty:"A",default:"-5",page:"197"},
        freightHandling:{skillId:"freightHandling",name:"Freight Handling",attributeId:"iq",difficulty:"A",default:"-5",page:"197"},
        gambling:{skillId:"gambling",name:"Gambling",attributeId:"iq",difficulty:"A",default:"-5",page:"197"},
        games:{skillId:"games",name:"Games",attributeId:"iq",difficulty:"E",default:"-4",page:"197"},
        gardening:{skillId:"gardening",name:"Gardening",attributeId:"iq",difficulty:"E",default:"-4",page:"197"},
        garrote:{skillId:"garrote",name:"Garrote",attributeId:"dx",difficulty:"E",default:"-4",page:"197"},
        geography:{skillId:"geography",name:"Geography",attributeId:"iq",difficulty:"H",default:"-6",page:"198"},
        geology:{skillId:"geology",name:"Geology",attributeId:"iq",difficulty:"H",default:"-6",page:"198"},
        gesture:{skillId:"gesture",name:"Gesture",attributeId:"iq",difficulty:"E",default:"-4",page:"198"},
        groupPerformance:{skillId:"groupPerformance",name:"Group Performance",attributeId:"iq",difficulty:"A",default:"-5",page:"198"},
        gunner:{skillId:"gunner",name:"Gunner",attributeId:"dx",difficulty:"E",default:"-4",page:"198"},
        gunsPistol:{skillId:"gunsPistol",name:"Guns-Pistol",attributeId:"dx",difficulty:"E",default:"-4",page:"198"},
        gunsRifle:{skillId:"gunsRifle",name:"Guns-Rifle",attributeId:"dx",difficulty:"E",default:"-4",page:"198"},
        hazardousMaterials:{skillId:"hazardousMaterials",name:"Hazardous Materials",attributeId:"iq",difficulty:"A",default:"-5",page:"199"},
        heraldry:{skillId:"heraldry",name:"Heraldry",attributeId:"iq",difficulty:"A",default:"-5",page:"199"},
        herbLore:{skillId:"herbLore",name:"Herb Lore",attributeId:"iq",difficulty:"VH",default:"-999",page:"199"},
        hiddenLore:{skillId:"hiddenLore",name:"Hidden Lore",attributeId:"iq",difficulty:"A",default:"-999",page:"199"},
        hiking:{skillId:"hiking",name:"Hiking",attributeId:"ht",difficulty:"A",default:"-5",page:"200"},
        history:{skillId:"history",name:"History",attributeId:"iq",difficulty:"H",default:"-6",page:"200"},
        hobbySkillMental:{skillId:"hobbySkillMental",name:"Mental Hobby Skill",attributeId:"iq",difficulty:"E",default:"DX-4",page:"200"},
        hobbySkillPhysical:{skillId:"hobbySkillPhysical",name:"Physical Hobby Skill",attributeId:"dx",difficulty:"E",default:"-4",page:"200"},
        holdout:{skillId:"holdout",name:"Holdout",attributeId:"iq",difficulty:"A",default:"-5",page:"200"},
        housekeeping:{skillId:"housekeeping",name:"Housekeeping",attributeId:"iq",difficulty:"E",default:"-4",page:"200"},
        hypnotism:{skillId:"hypnotism",name:"Hypnotism",attributeId:"iq",difficulty:"H",default:"-999",page:"201"},
        immovableStance:{skillId:"immovableStance",name:"Immovable Stance",attributeId:"dx",difficulty:"H",default:"-999",page:"201"},
        innateAttack:{skillId:"innateAttack",name:"Innate Attack",attributeId:"dx",difficulty:"E",default:"-4",page:"201"},
        intelligenceAnalysis:{skillId:"intelligenceAnalysis",name:"Intelligence Analysis",attributeId:"iq",difficulty:"H",default:"-6",page:"201"},
        interrogation:{skillId:"interrogation",name:"Interrogation",attributeId:"iq",difficulty:"A",default:"-5",page:"202"},
        intimidation:{skillId:"intimidation",name:"Intimidation",attributeId:"will",difficulty:"A",default:"-5",page:"202"},
        invisibilityArt:{skillId:"invisibilityArt",name:"Invisibility Art",attributeId:"iq",difficulty:"VH",default:"-999",page:"202"},
        jeweler:{skillId:"jeweler",name:"Jeweler",attributeId:"iq",difficulty:"H",default:"-6",page:"203"},
        jitteSai:{skillId:"jitteSai",name:"Jitte/Sai",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        judo:{skillId:"judo",name:"Judo",attributeId:"dx",difficulty:"H",default:"-999",page:"203"},
        jumping:{skillId:"jumping",name:"Jumping",attributeId:"dx",difficulty:"E",default:"-999",page:"203"},
        karate:{skillId:"karate",name:"Karate",attributeId:"dx",difficulty:"H",default:"-999",page:"203"},
        kiai:{skillId:"kiai",name:"Kiai",attributeId:"ht",difficulty:"H",default:"-999",page:"203"},
        knife:{skillId:"knife",name:"Knife",attributeId:"dx",difficulty:"E",default:"-999",page:"208"},
        knotTying:{skillId:"knotTying",name:"Knot-Tying",attributeId:"dx",difficulty:"E",default:"-4",page:"203"},
        kusari:{skillId:"kusari",name:"Kusari",attributeId:"dx",difficulty:"H",default:"-999",page:"209"},
        lance:{skillId:"lance",name:"Lance",attributeId:"dx",difficulty:"A",default:"-5",page:"204"},
        lasso:{skillId:"lasso",name:"Lasso",attributeId:"dx",difficulty:"A",default:"-999",page:"204"},
        law:{skillId:"law",name:"Law",attributeId:"iq",difficulty:"H",default:"-6",page:"204"},
        leadership:{skillId:"leadership",name:"Leadership",attributeId:"iq",difficulty:"A",default:"-5",page:"204"},
        leatherworking:{skillId:"leatherworking",name:"Leatherworking",attributeId:"dx",difficulty:"E",default:"-4",page:"205"},
        lifting:{skillId:"lifting",name:"Lifting",attributeId:"ht",difficulty:"A",default:"-999",page:"205"},
        lightWalk:{skillId:"lightWalk",name:"Light Walk",attributeId:"dx",difficulty:"H",default:"-999",page:"205"},
        linguistics:{skillId:"linguistics",name:"Linguistics",attributeId:"iq",difficulty:"H",default:"-999",page:"205"},
        lipReading:{skillId:"lipReading",name:"Lip Reading",attributeId:"per",difficulty:"A",default:"-1",page:"205"},
        liquidProjector:{skillId:"liquidProjector",name:"Liquid Projector",attributeId:"dx",difficulty:"E",default:"-4",page:"205"},
        literature:{skillId:"literature",name:"Literature",attributeId:"iq",difficulty:"H",default:"-6",page:"205"},
        lockpicking:{skillId:"lockpicking",name:"Lockpicking",attributeId:"iq",difficulty:"A",default:"-5",page:"206"},
        machinist:{skillId:"machinist",name:"Machinist",attributeId:"iq",difficulty:"A",default:"-5",page:"206"},
        mainGauche:{skillId:"mainGauche",name:"Main-Gauche",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        makeup:{skillId:"makeup",name:"Makeup",attributeId:"iq",difficulty:"E",default:"-4",page:"206"},
        marketAnalysis:{skillId:"marketAnalysis",name:"Market Analysis",attributeId:"iq",difficulty:"H",default:"-6",page:"207"},
        masonry:{skillId:"masonry",name:"Masonry",attributeId:"iq",difficulty:"E",default:"-4",page:"207"},
        mathematics:{skillId:"mathematics",name:"Mathematics",attributeId:"iq",difficulty:"H",default:"-6",page:"207"},
        mechanic:{skillId:"mechanic",name:"Mechanic",attributeId:"iq",difficulty:"A",default:"-5",page:"207"},
        meditation:{skillId:"meditation",name:"Meditation",attributeId:"will",difficulty:"H",default:"-6",page:"207"},
        mentalStrength:{skillId:"mentalStrength",name:"Mental Strength",attributeId:"will",difficulty:"E",default:"-999",page:"209"},
        merchant:{skillId:"merchant",name:"Merchant",attributeId:"iq",difficulty:"A",default:"-5",page:"209"},
        metallurgy:{skillId:"metallurgy",name:"Metallurgy",attributeId:"iq",difficulty:"H",default:"-999",page:"209"},
        meteorology:{skillId:"meteorology",name:"Meteorology",attributeId:"iq",difficulty:"A",default:"-5",page:"209"},
        mimicry:{skillId:"mimicry",name:"Mimicry",attributeId:"iq",difficulty:"H",default:"-6",page:"210"},
        mindBlock:{skillId:"mindBlock",name:"Mind Block",attributeId:"will",difficulty:"A",default:"-5",page:"210"},
        monowireWhip:{skillId:"monowireWhip",name:"Monowire Whip",attributeId:"dx",difficulty:"H",default:"-999",page:"209"},
        mount:{skillId:"mount",name:"Mount",attributeId:"dx",difficulty:"A",default:"-5",page:"210"},
        musicalComposition:{skillId:"musicalComposition",name:"Musical Composition",attributeId:"iq",difficulty:"H",default:"-999",page:"210"},
        musicalInfluence:{skillId:"musicalInfluence",name:"Musical Influence",attributeId:"iq",difficulty:"VH",default:"-999",page:"210"},
        musicalInstrument:{skillId:"musicalInstrument",name:"Musical Instrument",attributeId:"iq",difficulty:"H",default:"-999",page:"211"},
        naturalist:{skillId:"naturalist",name:"Naturalist",attributeId:"iq",difficulty:"H",default:"-6",page:"211"},
        navigation:{skillId:"navigation",name:"Navigation",attributeId:"iq",difficulty:"A",default:"-999",page:"211"},
        nbcSuit:{skillId:"nbcSuit",name:"NBC Suit",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        net:{skillId:"net",name:"Net",attributeId:"dx",difficulty:"H",default:"-999",page:"211"},
        observation:{skillId:"observation",name:"Observation",attributeId:"per",difficulty:"A",default:"-5",page:"211"},
        occultism:{skillId:"occultism",name:"Occultism",attributeId:"iq",difficulty:"A",default:"-5",page:"212"},
        packing:{skillId:"packing",name:"Packing",attributeId:"iq",difficulty:"A",default:"-5",page:"212"},
        paleontology:{skillId:"paleontology",name:"Paleontology",attributeId:"iq",difficulty:"H",default:"-999",page:"212"},
        panhandling:{skillId:"panhandling",name:"Panhandling",attributeId:"iq",difficulty:"E",default:"-4",page:"212"},
        parachuting:{skillId:"parachuting",name:"Parachuting",attributeId:"dx",difficulty:"E",default:"-4",page:"212"},
        parryMissileWeapons:{skillId:"parryMissileWeapons",name:"Parry Missile Weapons",attributeId:"dx",difficulty:"H",default:"-999",page:"212"},
        performance:{skillId:"performance",name:"Performance",attributeId:"iq",difficulty:"A",default:"-5",page:"212"},
        persuade:{skillId:"persuade",name:"Persuade",attributeId:"will",difficulty:"H",default:"-999",page:"191"},
        pharmacy:{skillId:"pharmacy",name:"Pharmacy",attributeId:"iq",difficulty:"H",default:"-6",page:"213"},
        philosophy:{skillId:"philosophy",name:"Philosophy",attributeId:"iq",difficulty:"H",default:"-6",page:"213"},
        photography:{skillId:"photography",name:"Photography",attributeId:"iq",difficulty:"A",default:"-5",page:"213"},
        physician:{skillId:"physician",name:"Physician",attributeId:"iq",difficulty:"H",default:"-7",page:"213"},
        physics:{skillId:"physics",name:"Physics",attributeId:"iq",difficulty:"VH",default:"-6",page:"213"},
        physiology:{skillId:"physiology",name:"Physiology",attributeId:"iq",difficulty:"H",default:"-6",page:"213"},
        pickpocket:{skillId:"pickpocket",name:"Pickpocket",attributeId:"dx",difficulty:"H",default:"-6",page:"213"},
        piloting:{skillId:"piloting",name:"Piloting",attributeId:"dx",difficulty:"A",default:"IQ-6",page:"214"},
        poetry:{skillId:"poetry",name:"Poetry",attributeId:"iq",difficulty:"A",default:"-5",page:"214"},
        poisons:{skillId:"poisons",name:"Poisons",attributeId:"iq",difficulty:"H",default:"-6",page:"214"},
        polearm:{skillId:"polearm",name:"Polearm",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        politics:{skillId:"politics",name:"Politics",attributeId:"iq",difficulty:"A",default:"-5",page:"215"},
        powerBlow:{skillId:"powerBlow",name:"Power Blow",attributeId:"will",difficulty:"H",default:"-999",page:"215"},
        pressurePoints:{skillId:"pressurePoints",name:"Pressure Points",attributeId:"iq",difficulty:"H",default:"-999",page:"215"},
        pressureSecrets:{skillId:"pressureSecrets",name:"Pressure Secrets",attributeId:"iq",difficulty:"VH",default:"-999",page:"215"},
        professionalSkillMental:{skillId:"professionalSkillMental",name:"Professional Skill Mental",attributeId:"iq",difficulty:"A",default:"-999",page:"215"},
        professionalSkillPhysical:{skillId:"professionalSkillPhysical",name:"Professional Skill Physical",attributeId:"iq",difficulty:"A",default:"-999",page:"215"},
        propaganda:{skillId:"propaganda",name:"Propaganda",attributeId:"iq",difficulty:"A",default:"-5",page:"216"},
        prospecting:{skillId:"prospecting",name:"Prospecting",attributeId:"iq",difficulty:"A",default:"-5",page:"216"},
        psychology:{skillId:"psychology",name:"Psychology",attributeId:"iq",difficulty:"H",default:"-6",page:"216"},
        publicSpeaking:{skillId:"publicSpeaking",name:"Public Speaking",attributeId:"iq",difficulty:"A",default:"-5",page:"216"},
        push:{skillId:"push",name:"Push",attributeId:"dx",difficulty:"H",default:"-999",page:"216"},
        rapier:{skillId:"rapier",name:"Rapier",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        religiousRitual:{skillId:"religiousRitual",name:"Religious Ritual",attributeId:"iq",difficulty:"H",default:"-999",page:"217"},
        research:{skillId:"research",name:"Research",attributeId:"iq",difficulty:"A",default:"-5",page:"217"},
        riding:{skillId:"riding",name:"Riding",attributeId:"dx",difficulty:"A",default:"-5",page:"217"},
        ritualMagic:{skillId:"ritualMagic",name:"Ritual Magic",attributeId:"iq",difficulty:"VH",default:"-999",page:"218"},
        running:{skillId:"running",name:"Running",attributeId:"ht",difficulty:"A",default:"-5",page:"218"},
        saber:{skillId:"saber",name:"Saber",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        savoirFaire:{skillId:"savoirFaire",name:"Savoir-Faire",attributeId:"iq",difficulty:"E",default:"-4",page:"218"},
        scrounging:{skillId:"scrounging",name:"Scrounging",attributeId:"per",difficulty:"E",default:"-4",page:"218"},
        scuba:{skillId:"scuba",name:"Scuba",attributeId:"iq",difficulty:"A",default:"-5",page:"219"},
        seamanship:{skillId:"seamanship",name:"Seamanship",attributeId:"iq",difficulty:"E",default:"-4",page:"185"},
        search:{skillId:"search",name:"Search",attributeId:"per",difficulty:"A",default:"-5",page:"219"},
        sewing:{skillId:"sewing",name:"Sewing",attributeId:"dx",difficulty:"E",default:"-4",page:"219"},
        sexAppeal:{skillId:"sexAppeal",name:"Sex Appeal",attributeId:"ht",difficulty:"A",default:"-3",page:"219"},
        shadowing:{skillId:"shadowing",name:"Shadowing",attributeId:"iq",difficulty:"A",default:"-5",page:"219"},
        shield:{skillId:"shield",name:"Shield",attributeId:"dx",difficulty:"E",default:"-4",page:"220"},
        shipHandling:{skillId:"shipHandling",name:"Shiphandling",attributeId:"iq",difficulty:"H",default:"-6",page:"220"},
        shortsword:{skillId:"shortsword",name:"Shortsword",attributeId:"dx",difficulty:"A",default:"-999",page:"209"},
        singing:{skillId:"singing",name:"Singing",attributeId:"ht",difficulty:"E",default:"-4",page:"220"},
        skating:{skillId:"skating",name:"Skating",attributeId:"ht",difficulty:"H",default:"-6",page:"220"},
        skiing:{skillId:"skiing",name:"Skiing",attributeId:"ht",difficulty:"H",default:"-6",page:"221"},
        sleightOfHand:{skillId:"sleightOfHand",name:"Sleight of Hand",attributeId:"dx",difficulty:"H",default:"-999",page:"221"},
        sling:{skillId:"sling",name:"Sling",attributeId:"dx",difficulty:"H",default:"-6",page:"221"},
        smallsword:{skillId:"smallsword",name:"Smallsword",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        smith:{skillId:"smith",name:"Smith",attributeId:"iq",difficulty:"A",default:"-5",page:"221"},
        smuggling:{skillId:"smuggling",name:"Smuggling",attributeId:"iq",difficulty:"A",default:"-5",page:"221"},
        sociology:{skillId:"sociology",name:"Sociology",attributeId:"iq",difficulty:"H",default:"-6",page:"221"},
        soldier:{skillId:"soldier",name:"Soldier",attributeId:"iq",difficulty:"A",default:"-5",page:"221"},
        spacer:{skillId:"spacer",name:"Spacer",attributeId:"iq",difficulty:"E",default:"-4",page:"185"},
        spear:{skillId:"spear",name:"Spear",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        spearThrower:{skillId:"spearThrower",name:"Spear Thrower",attributeId:"dx",difficulty:"A",default:"-5",page:"222"},
        speedReading:{skillId:"speedReading",name:"Speed-Reading",attributeId:"iq",difficulty:"A",default:"-999",page:"222"},
        sports:{skillId:"sports",name:"Sports",attributeId:"dx",difficulty:"A",default:"-999",page:"222"},
        staff:{skillId:"staff",name:"Staff",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        stageCombat:{skillId:"stageCombat",name:"Stage Combat",attributeId:"dx",difficulty:"A",default:"-999",page:"222"},
        stealth:{skillId:"stealth",name:"Stealth",attributeId:"dx",difficulty:"A",default:"-5",page:"222"},
        strategy:{skillId:"strategy",name:"Strategy",attributeId:"iq",difficulty:"H",default:"-6",page:"222"},
        streetwise:{skillId:"streetwise",name:"Streetwise",attributeId:"iq",difficulty:"A",default:"-5",page:"223"},
        submarine:{skillId:"submarine",name:"Submarine",attributeId:"dx",difficulty:"A",default:"IQ-6",page:"223"},
        submariner:{skillId:"submariner",name:"Submariner",attributeId:"iq",difficulty:"E",default:"-4",page:"185"},
        suggest:{skillId:"suggest",name:"Suggest",attributeId:"will",difficulty:"H",default:"-999",page:"191"},
        sumoWrestling:{skillId:"sumoWrestling",name:"Sumo Wrestling",attributeId:"dx",difficulty:"A",default:"-999",page:"223"},
        surgery:{skillId:"surgery",name:"Surgery",attributeId:"iq",difficulty:"VH",default:"-999",page:"223"},
        survival:{skillId:"survival",name:"Survival",attributeId:"per",difficulty:"A",default:"-5",page:"223"},
        swayEmotions:{skillId:"swayEmotions",name:"Sway Emotions",attributeId:"will",difficulty:"H",default:"-999",page:"192"},
        swimming:{skillId:"swimming",name:"Swimming",attributeId:"ht",difficulty:"E",default:"-4",page:"224"},
        symbolDrawing:{skillId:"symbolDrawing",name:"Symbol Drawing",attributeId:"iq",difficulty:"H",default:"-999",page:"224"},
        tactics:{skillId:"tactics",name:"Tactics",attributeId:"iq",difficulty:"H",default:"-6",page:"224"},
        teaching:{skillId:"teaching",name:"Teaching",attributeId:"iq",difficulty:"A",default:"-5",page:"224"},
        teamster:{skillId:"teamster",name:"Teamster",attributeId:"iq",difficulty:"A",default:"-5",page:"225"},
        thaumatology:{skillId:"thaumatology",name:"Thaumatology",attributeId:"iq",difficulty:"VH",default:"-7",page:"225"},
        theology:{skillId:"theology",name:"Theology",attributeId:"iq",difficulty:"H",default:"-6",page:"226"},
        throwing:{skillId:"throwing",name:"Throwing",attributeId:"dx",difficulty:"A",default:"-3",page:"226"},
        throwingArt:{skillId:"throwingArt",name:"Throwing Art",attributeId:"dx",difficulty:"H",default:"-999",page:"226"},
        thrownWeapon:{skillId:"thrownWeapon",name:"Thrown Weapon",attributeId:"dx",difficulty:"E",default:"-4",page:"226"},
        tonfa:{skillId:"tonfa",name:"Tonfa",attributeId:"dx",difficulty:"A",default:"-999",page:"209"},
        tracking:{skillId:"tracking",name:"Tracking",attributeId:"per",difficulty:"A",default:"-5",page:"226"},
        traps:{skillId:"traps",name:"Traps",attributeId:"iq",difficulty:"A",default:"-5",page:"226"},
        twoHandedAxeMace:{skillId:"twoHandedAxeMace",name:"Two-Handed Axe/Mace",attributeId:"dx",difficulty:"A",default:"-999",page:"208"},
        twoHandedFlail:{skillId:"twoHandedFlail",name:"Two-Handed Flail",attributeId:"dx",difficulty:"H",default:"-999",page:"208"},
        twoHandedSword:{skillId:"twoHandedSword",name:"Two-Handed Sword",attributeId:"dx",difficulty:"A",default:"-999",page:"209"},
        typing:{skillId:"typing",name:"Typing",attributeId:"dx",difficulty:"E",default:"-4",page:"228"},
        urbanSurvival:{skillId:"urbanSurvival",name:"Urban Survival",attributeId:"per",difficulty:"A",default:"-5",page:"228"},
        vaccSuit:{skillId:"vaccSuit",name:"Vacc Suit",attributeId:"dx",difficulty:"A",default:"-5",page:"192"},
        ventriloquism:{skillId:"ventriloquism",name:"Ventriloquism",attributeId:"iq",difficulty:"H",default:"-999",page:"228"},
        veterinary:{skillId:"veterinary",name:"Veterinary",attributeId:"iq",difficulty:"H",default:"-999",page:"228"},
        weatherSense:{skillId:"weatherSense",name:"Weather Sense",attributeId:"iq",difficulty:"A",default:"-5",page:"209"},
        weirdScience:{skillId:"weirdScience",name:"Weird Science",attributeId:"iq",difficulty:"VH",default:"-999",page:"228"},
        whip:{skillId:"whip",name:"Whip",attributeId:"dx",difficulty:"A",default:"-999",page:"209"},
        wrestling:{skillId:"wrestling",name:"Wrestling",attributeId:"dx",difficulty:"A",default:"-999",page:"228"},
        writing:{skillId:"writing",name:"Writing",attributeId:"iq",difficulty:"A",default:"-5",page:"228"},
        zenArchery:{skillId:"zenArchery",name:"Zen Archery",attributeId:"iq",difficulty:"VH",default:"-999",page:"228"}
    };

const SkillRelativeStart = {
    "E": 0,
    "A": -1,
    "H": -2,
    "VH": -3
}

const SkillDifficultyCostProgression = [1,2,4,8,12,16,20,24,28];


type SkillsStore = {
    list: SkillListStore;
    relativeStart: {[difficulty:string]:number};
    difficultyCostProgression: number[];
}


export const SystemSkillsStoreInitialState: SkillsStore = {
    list: SystemSkillsListStoreInitialState,
    relativeStart: SkillRelativeStart,
    difficultyCostProgression: SkillDifficultyCostProgression
}